version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  reviewers:
  - liyasthomas
  labels:
  - Dependency upgrade
  ignore:
  - dependency-name: nuxt-i18n
    versions:
    - 6.18.0
    - 6.19.0
    - 6.20.0
    - 6.20.1
    - 6.20.2
    - 6.20.6
    - 6.21.1
    - 6.22.2
    - 6.22.3
    - 6.24.0
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.9
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.4.0
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.0
    - 6.8.0
    - 7.0.0
    - 7.1.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: yargs-parser
    versions:
    - 20.2.4
    - 20.2.5
    - 20.2.6
  - dependency-name: start-server-and-test
    versions:
    - 1.11.7
    - 1.12.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
